### ISSUE TITLE
I installed the latest addon and only see  "Newest Videos" 

### ISSUE THREAD

**Issue by ktaragorn** [ruuk/plugin.video.geekandsundry#1]
How would I see all shows? Is the official repos out of date?

**Comment by ktaragorn** [comment]
looks to be the case, please update :)

**Comment by ktaragorn** [comment]
The version in ur repo doesnt work at all..

**Comment by ktaragorn** [comment]
dum dum duuum...... geek and sundry is blocking automated requests with 403. Only "Newest Shows" seems to be allowed. I can submit a pull request added User agent which lets me get past.. for now..

**Comment by ktaragorn** [comment]
More work is needed. I see that the website divides the show episodes into pages, i dont see any such logic in your code

**Comment by ruuk** [comment]
Thanks for the report.
The site was heavily modified since I last worked on the addon. Fixed version now committed to the official repository.

**Comment by ktaragorn** [comment]
Hey @ruuk .. I didnt see the update as of couple of hours ago.. but regardless the latest version is even more broken.. Their site serves 403 on automated crawlers.. please check my comments

**Comment by ktaragorn** [comment]
Ah didnt notice u made couple of changes :P please ignore my last and my PR..

**Comment by ktaragorn** [comment]
I do have 1 refactoring that might help.. your code has a repeated pattern of get cached -> if not -> fetch page -> save in cache. I extracted this into a method
