### ISSUE TITLE
I am facing errors in atleast 1 show - Co-optitude

### ISSUE THREAD

**Issue by ktaragorn** [ruuk/plugin.video.geekandsundry#3]
Recently I was using the addon, while I noticed that for atleast that particular show, the same video in "Newest videos" plays fine, but when located in the "Show" itself, the latest ones fail with errors, and also appear to be named differently.

**Comment by ktaragorn** [comment]
And Table Top. I am trying to debug it right now.

Findings so far. Trying on Secret of evermore video, Logic for brightcove video is breaking since they seem to have added a script tag in front of the one u want.
Replacing  
`vidScript = vidDiv.script`
with  
`vidScript = vidDiv.select("script")[1]`

Seems to fix both shows for me.. Let me test some more and see if there is a better fix for it

**Comment by ktaragorn** [comment]
Better fix is 

```
    scripts = vidDiv.select("script")
    checkForBrightcovePlayer = lambda script: script.get("src") and script.get("src").startswith("//players.brightcove.net")
    vidScript = filter(checkForBrightcovePlayer, scripts)[0]
```

This checks for the script we need, not the first or the second script. Hopefully this is more robust

**Comment by ktaragorn** [comment]
Facing another issue, gonna keep looking. 

At some point it might be a better thing for many reasons to move to youtube direct - https://www.youtube.com/playlist?list=PL4F80C7D2DC8D9B6C
This would be faster by far than looking at 10 different pages, and also doesnt bother with the extended interviews and stuff if u dont want it

**Comment by ruuk** [comment]
I haven't looked at the site lately, but the main issue with using the youtube playlists is that you either need to somehow find them based on the list of shows from the g&s site or hardcode then in - which doesn't allow the add-on to dynamically react to show additions (though it will probably still make maintainence easier so might be the way to go). When I first wrote the add-on the site was much easier to scrape :)

Much of the add-on could really be re-written as I honestly slapped it together pretty quickly initially.

**Comment by ktaragorn** [comment]
If we go with hardcoded route, it may make sense to make it depend on a remote file in say your dropbox which contains the mapping. That would make it even easier to update? 

Also I am looking at https://xbmcswift2.readthedocs.org/en/latest/patterns.html#caching. How about we use that for caching all over the place? Caching for a day seems reasonable and we can pretty much cache everything, including the `getPage` method.

**Comment by ruuk** [comment]
If they were adding shows more often it would make more sense. But it would also add more complexity and I can push directly to the Kodi repo so it's easy to update.

The caching is a good idea. I haven't taken much time to look into that part of xbmcswift2, but as I recall it didn't seem too difficult to use. I think this add-on may have been my first experiment with the library :)
